apiVersion: apps/v1
kind: Deployment
metadata:
  name: student3-deployment
spec:
  selector:
    matchLabels:
      app: student3
  template:
    metadata:
      labels:
        app: student3
    spec:
      containers:
      - name: student3
        image: registry.tanzu.dk/ops2devops/student3:v1
